homepage and component page
js-tasks-ru/htmlcss-20210409_eg-nosach pull request #5
Opened 2021-05-11 06:58 UTC by egor3333

2021-05-11 06:58 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-05-20 08:28 UTC, egor3333 commented
I made tabs without scripts

2021-05-20 11:33 UTC, GSemikozov requested changes

2021-05-20 11:33 UTC, GSemikozov commented on components/preview-component.css
> +  overflow: scroll;
чтобы скрол отображался только когда это нужно - лучше использовать `auto`

2021-05-20 11:33 UTC, GSemikozov commented on assets/css/main.css
> +/* media template */
удалим?

2021-05-20 11:39 UTC, egor3333 commented on components/preview-component.css
> +  overflow: scroll;
Убрал)

2021-05-20 11:39 UTC, egor3333 commented on assets/css/main.css
> +/* media template */
Удалил)

2021-05-20 11:39 UTC, egor3333 commented
Можно проверять)

2021-05-23 12:08 UTC, GSemikozov approved these changes

2021-05-23 12:08 UTC, merged